---
output:
  html_document:
    highlight: pygments
params:
  file: NULL
  sheet: NULL
  title: NULL
title: "`r params$title`"
---
<!-- https://stackoverflow.com/questions/31861569/setting-document-title-in-rmarkdown-from-parameters -->


<!-- https://stackoverflow.com/questions/14695892/change-code-block-color-in-knitr-markdown -->
<style>
.table>tbody>tr>td {
  padding: 0;
  /*border-top: none;*/
}

/*div*/
div.sourceCode {
  margin: 0;
}

pre {
  padding: 0;
  background-color: white;
  border: none;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

<!-- https://stackoverflow.com/questions/14695892/change-code-block-color-in-knitr-markdown -->
```{r, echo=F}
library(glue)
library(tidyverse)
library(readxl)
library(htmltools)
library(magrittr)
library(googlesheets4)
library(rlist)
library(readODS)

# https://stackoverflow.com/questions/9281323/zip-or-enumerate-in-r
zip <- function(...) {
  mapply(list, ..., SIMPLIFY = FALSE)
}

# Need to add knitr options at some point to be able to specify
# if code chunks should be run
chunk <- function(x) {
  # Glue treats double bracket as literals
  gsub("{", "{{", x, fixed = T) %>%
    gsub("}", "}}", ., fixed = T) %>% {
      glue("\n\n```{{r echo=T, eval=F}}\n{.}\n```\n\n") # Two newlines needed: 
      # "Leading whitespace and blank lines from the first and last lines are automatically trimmed."
      # And Rmarkdown requires chunks on and at the start of their own lines.
    }
}

# https://stackoverflow.com/questions/10937218/how-to-show-multiline-text-in-a-table-cell
data_to_html <- function(df) {
  tags$table(class="table",  # Bootstrap class used by rmarkdown
             tags$tbody(
               apply(df, 1, function(row) {
                 # Can this be applied to the row instead?
                 # if (grepl("\n", row["Code"])) td_args$style <- "white-space:pre"
                 
                 row["Code"] %<>% chunk
                 
                 # td_args <- list(class="col-xs-6")
                 # tags$tr(lapply(row, function(x) do.call(tags$td, c(td_args, x))))
                 
                 # https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp
                 # Bootstrap column classes indicate how many of 12 columns to span
                 tags$tr(tags$td(class="col-xs-8", unname(row["Description"])),
                         tags$td(class="col-xs-4", unname(row["Code"]))
                 )
               })
             )
  )
}

# TODO: For each cheat sheet, change privacy to allow anyone with link to view

# Downloaded from RCheat google sheet
# sheets_deauth() # No need to authenticate for sheets that are readably by anyone with the link
# uri <- "https://docs.google.com/spreadsheets/d/15qbAr-6b3qBBi-6iv60NbfJ1eLC3eeqM8PIU0DZxup0/edit#gid=0"
# data <- read_sheet(uri, sheet = "Cheat") %>%
#   replace_na(list(Description=""))
#cheatsheet <- "/Users/justinkroes/Sync/Cheat/RCheat.xlsx"
data <- read_excel(params$file, sheet = params$sheet)

# Extract headers
headers <- filter(data, str_detect(Description, "^\\*"))

split_data <- data %>%
  # Get row number of header rows
  mutate(x = ifelse(str_detect(data$Description, "^\\*.+"), row_number(), NA)) %>%
  # Group rows using each header's row number
  fill(x) %>%
  # Remove header rows
  anti_join(headers, by = "Description") %>% 
  # Split non-headers based on groups
  split(.$x) %>%
  # Remove groups (column)
  lapply(function(df) select(df, -x))

# Construct HTML headers
header_text <- gsub("*", "", headers$Description, fixed = T)
header_levels <- paste0("h", str_count(headers$Description, "\\*"))
html_headers <- mapply(function(x,y) do.call(eval(parse(text=x)), list(y)), 
                       header_levels, 
                       header_text,
                       SIMPLIFY = F, 
                       USE.NAMES = F)
# html_headers <- lapply(names(split_data), h1)

html_tables <- lapply(split_data, data_to_html)
list.zip(html_headers, html_tables) %>%
  tags$body(.) %>% # Apparently flattens nested lists
  as.character %>%
  sub("\n</body>", "", .) %>% # Remove outer body tags
  sub("<body>\n", "", .) %>%
  writeLines("__temp__.html") # Write as-is; compare to save_html

# TODO: Enable footnotes from Footnotes sheet
# https://html.com/tags/sup/
```

```{r child="__temp__.html"}
```

<!-- TODO: Consider using fixed width columns to maintain consistent widths across tables -->
